import jsPDF from 'jspdf';

export const generateSamplePDF = (pdfName, classNum) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Set colors
  doc.setDrawColor(59, 130, 246); // primary color
  doc.setLineWidth(1);

  // Header
  doc.setFillColor(59, 130, 246);
  doc.rect(0, 0, pageWidth, 30, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text(pdfName, pageWidth / 2, 20, { align: 'center' });

  // Reset text color
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  yPosition = 50;

  // Title
  doc.text(`Class ${classNum} Study Material`, 20, yPosition);
  yPosition += 20;

  // Content sections based on PDF name
  const sections = generateSections(pdfName, classNum);
  
  sections.forEach((section) => {
    // Check if we need a new page
    if (yPosition > pageHeight - 40) {
      doc.addPage();
      yPosition = 20;
    }

    // Section title
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text(section.title, 20, yPosition);
    yPosition += 10;

    // Section content
    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(section.content, pageWidth - 40);
    lines.forEach((line) => {
      if (yPosition > pageHeight - 30) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(line, 20, yPosition);
      yPosition += 8;
    });
    yPosition += 10;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(
    `Generated by StudyBracket.com | Class ${classNum}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  return doc;
};

const generateSections = (pdfName, classNum) => {
  const baseContent = {
    'Mathematics Formula Sheet': [
      {
        title: '1. Algebraic Formulas',
        content: '(a+b)² = a² + 2ab + b², (a-b)² = a² - 2ab + b², a² - b² = (a+b)(a-b), (a+b)³ = a³ + 3a²b + 3ab² + b³'
      },
      {
        title: '2. Trigonometric Formulas',
        content: 'sin²θ + cos²θ = 1, sin(A+B) = sinA cosB + cosA sinB, cos(A+B) = cosA cosB - sinA sinB'
      },
      {
        title: '3. Calculus Formulas',
        content: 'd/dx(xⁿ) = nxⁿ⁻¹, ∫xⁿ dx = xⁿ⁺¹/(n+1) + C, d/dx(sin x) = cos x'
      }
    ],
    'Science Important Diagrams': [
      {
        title: '1. Cell Structure',
        content: 'The cell is the basic unit of life. It contains nucleus (controls cell activities), mitochondria (power house), endoplasmic reticulum (protein synthesis), and other organelles.'
      },
      {
        title: '2. Photosynthesis',
        content: 'Process: 6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂. Light-dependent reactions occur in thylakoids, dark reactions occur in stroma.'
      },
      {
        title: '3. Nervous System',
        content: 'Composed of CNS (brain and spinal cord) and PNS (peripheral nerves). Brain controls all body functions and processes information from sense organs.'
      }
    ],
    'English Grammar Notes': [
      {
        title: '1. Parts of Speech',
        content: 'Noun: names of person, place, thing. Verb: action or state. Adjective: describes noun. Adverb: describes verb/adjective/adverb. Pronoun: replaces noun.'
      },
      {
        title: '2. Tenses',
        content: 'Simple Present: I go, Present Continuous: I am going, Present Perfect: I have gone, Simple Past: I went, Past Continuous: I was going, Past Perfect: I had gone'
      },
      {
        title: '3. Articles',
        content: 'Use "a" before consonant sounds, "an" before vowel sounds. "The" is used for specific/definite things. No article for non-specific/indefinite plural nouns.'
      }
    ],
    'Social Science Maps': [
      {
        title: '1. Indian Geography',
        content: 'India covers area of 3.27 million km². Bordered by Arabian Sea, Bay of Bengal, Indian Ocean. 28 states and 8 union territories. Capital: New Delhi.'
      },
      {
        title: '2. World Geography',
        content: 'Earth divided into 7 continents: Asia, Africa, Europe, North America, South America, Oceania, Antarctica. 195 countries. India is largest democracy.'
      },
      {
        title: '3. Climate Zones',
        content: 'Tropical (hot and humid), Subtropical (warm), Temperate (moderate), Cold (polar regions). India experiences monsoon climate - southwest and northeast monsoons.'
      }
    ],
    'Physics Formula Sheet': [
      {
        title: '1. Mechanics',
        content: 'F = ma, v = u + at, s = ut + ½at², v² = u² + 2as, p = mv, W = Fs, P = W/t, E = ½mv²'
      },
      {
        title: '2. Electricity',
        content: 'V = IR (Ohm\'s Law), P = VI, P = I²R, P = V²/R, ε = nΦ/t (Faraday\'s Law), F = BIl (Force on conductor)'
      },
      {
        title: '3. Optics',
        content: 'Ray phenomenon: Reflection (angle i = angle r), Refraction (n₁sinθ₁ = n₂sinθ₂), Lens formula: 1/f = 1/v + 1/u, M = h₂/h₁'
      }
    ],
    'Chemistry Reactions': [
      {
        title: '1. Oxidation-Reduction',
        content: 'Oxidation: loss of electrons, Reduction: gain of electrons. In redox reactions, oxidation and reduction occur simultaneously. Oxidation state changes indicate redox reactions.'
      },
      {
        title: '2. Organic Chemistry',
        content: 'Alkanes: CₙH₂ₙ₊₂, Alkenes: CₙH₂ₙ, Alkynes: CₙH₂ₙ₋₂. Functional groups: -OH (alcohol), -CHO (aldehyde), -CO- (ketone), -COOH (carboxylic acid)'
      },
      {
        title: '3. Periodic Table Trends',
        content: 'Atomic radius decreases across period, increases down group. Ionization energy increases across period, decreases down group. Electronegativity increases across period.'
      }
    ],
    'Biology Diagrams': [
      {
        title: '1. Human Digestive System',
        content: 'Mouth → Esophagus → Stomach → Small Intestine → Large Intestine → Rectum. Digestion involves mechanical breakdown and chemical breakdown by enzymes like amylase, pepsin, lipase.'
      },
      {
        title: '2. Circulatory System',
        content: 'Heart pumps blood. Arteries carry blood away from heart, veins bring blood back. Right side receives deoxygenated blood, left side pumps oxygenated blood.'
      },
      {
        title: '3. Reproductive System',
        content: 'Male: produces sperm in testes. Female: produces ovum in ovaries. Fertilization occurs in fallopian tube. Fertilized egg implants in uterus for development.'
      }
    ]
  };

  return baseContent[pdfName] || [
    {
      title: 'Study Material',
      content: `This is a sample PDF for ${pdfName}. This document contains important study notes and formulas for Class ${classNum}. Use this material for revision and exam preparation.`
    }
  ];
};

export const downloadPDF = (doc, fileName) => {
  doc.save(fileName + '.pdf');
};
